### ISSUE TITLE
background

### ISSUE THREAD

**Issue by bartaat** [ssjtux/vim-far#1]
hi i love this colour scheme for vim but when I set colours of my iterm to blue the vim becomes unreadable
how can I fix this?

**Comment by lycuid** [comment]
Hey @sollted,
I actually haven't been maintaining the repository as this was just one of my hobby side project, many years ago, but I wouldn't mind looking into it, if it's a minor thing.
So if you could:
  - try and run `:set termguicolors` and `:set notermguicolors` in vim and see if any of those solve your issue.
  - attach a screenshot of the issue for reference.

**Comment by bartaat** [comment]
Wow thanks the :set termguicolors fixed it

before
<img width="551" alt="before" src="https://user-images.githubusercontent.com/114848855/221394753-0ce72998-dbe2-4776-a508-41705bbd9cbb.png">
after
<img width="421" alt="after" src="https://user-images.githubusercontent.com/114848855/221394762-0d907564-60c0-46e8-b96a-ba6a7e3dd30f.png">
